language: node_js
node_js:
  - '12'
  - 'node'
install:
  - npm install
script:
  - npm test
  - npm run lint
deploy:
  provider: npm
  email: vote539@gmail.com
  api_key:
    secure: fPxzGqbb2y8nkwMBZaspNDw4OEJl44yffhTmU14he4pJx3hmKdwMt0lUbCpUIVsFwLvAb/RmyOlTqDd8TVvv/lgrWwQPMSaBsF2KzXj0wxR2soyKIiJaEDjoo+cyxpNJ2Qo6rCGi3kywTE7D+cIG6wbD4YgrxMdQDP0QiJix3ZCL4cgMwpTNztBWoGuWQ7tbXcTZA/QkTHJRmGbre4nwAcE3Z6O1jxEDnBEg5bayP+xeaw5jVLB7OrFltbGxBpH2OQ834H8L9yHKOvkobjjjIQ/zQL1xVwLtS844fo8hx1N9Fvjj8rsqoyNaiiwgkUCm+X6PibOZaZR5mvNPXbtmB41taisWKuRALe+gX1I1Kp7coMtXSyc04w7GHsd4j7pDzKAsBNlZbW3jkE4lx4lafFAFSFkH0L/Qm19YsLljBmRq5KGkIRHo8SkP3H4LBHcAa2JB1ELXQ5PufQhRmGGuOXV1DsYz0FkjPIjXaWnE0lhqUb+nCZ9GEJPWtcF1nfmmG+CzrOWceMa7a7QK2j84JWDTKRcFtNrFEPKcERzzrlBOxKZZolrEeJfTP7D3nu4n1nXxpUGda3K2L2V6QhvUL+dPukxByhXWZJgmw+/cZGfnkpLcnN2M9gJ6ZpGhal9qgP2puqLBa3MxfWwn2S7rrtzs5MkYqqf+FoX1qojdTLY=
  on:
    tags: true
    repo: sffc/easy-no-password
